version: "3.7"
services:
  jupyterlab:
    build: .
    container_name: docker-python
    volumes:
      - '.:/workspace'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
